# Generated by Django 5.1.4 on 2026-08-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                ("category", models.CharField(max_length=80)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                (
                    "tech",
                    models.JSONField(
                        blank=True, default=list, help_text="List of technologies"
                    ),
                ),
                ("problem", models.TextField()),
                ("solution", models.TextField()),
                ("results", models.TextField()),
                ("live_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
